story_dir: &story_dir generated_stories/example

story_writer:
    tool: qa_outline_story_writer
    cfg:
        max_conv_turns: 3
        num_outline: 4
        temperature: 0.5
    params:
        story_topic: "Time Management: A child learning how to manage their time effectively."
        main_role: "(no main role specified)"
        scene: "(no scene specified)"

speech_generation:
    tool: cosyvoice_tts
    cfg:
        sample_rate: &sample_rate 16000
    params:
        voice: xiaoyun


image_generation:
    tool: story_diffusion_t2i
    cfg:
        num_turns: 3
        api_type: "dashscope"  # Options: "dashscope", "openai", "stability", "replicate", "custom"
        api_key: ""  # Will use DASHSCOPE_API_KEY from environment (set in start.bat)
        llm: "qwen"
        height: &image_height 720
        width: &image_width 1280
        # Serial processing to comply with DashScope API rate limits (QPS: 0.5, concurrent: 1)
    params:
        seed: 112536
        style_name: "Storybook" # ['(No style)', 'Japanese Anime', 'Digital/Oil Painting', 'Pixar/Disney Character', 
                                #  'Photographic', 'Comic book', 'Line art', 'Black and White Film Noir', 'Isometric Rooms']


video_compose:
    tool: slideshow_video_compose
    cfg:
        {}
    params:
        height: *image_height
        width: *image_width
        story_dir: *story_dir
        fps: 24
        audio_sample_rate: 44100
        audio_codec: aac
        caption:
            font: resources/font/msyh.ttf
            # bg_color: LightGrey
            fontsize: 32
            color: white
            # stroke_color: white
            # stroke_width: 0.5
            max_length: 50
            workers: 4  # parallel TextClip render threads for subtitles
        # enable_captions: true  # Enable captions (default)
        slideshow_effect:
            fade_duration: 0.8
            slide_duration: 0.4
            zoom_speed: 0.5
            move_ratio: 0.9
    